import { library } from '@fortawesome/fontawesome-svg-core';
import {
	faArrowRightToBracket,
	faArrowRightFromBracket,
	faRotate,
	faMoon,
	faSun,
	faCartShopping,
	faGlobe,
	faHeart,
	faMagnifyingGlass,
	faAngleRight,
	faBars,
	faCheck,
	faTimes,
	faEye,
	faEyeSlash,
	faPaperPlane,
	faCircleQuestion,
	faChevronDown,
	faChevronRight,
	faFloppyDisk,
	faCircleInfo,
	faTriangleExclamation,
	faTimesCircle,
	faCircleCheck,
	faUser,
	faGear,
} from '@fortawesome/free-solid-svg-icons';
import { faGoogle, faGithub, faItchIo, faYoutube, faTwitch, faXTwitter } from '@fortawesome/free-brands-svg-icons';


library.add(
	faArrowRightToBracket,
	faArrowRightFromBracket,
	faRotate,
	faMoon,
	faSun,
	faCartShopping,
	faGlobe,
	faHeart,
	faMagnifyingGlass,
	faAngleRight,
	faBars,
	faCheck,
	faTimes,
	faEye,
	faEyeSlash,
	faPaperPlane,
	faCircleQuestion,
	faChevronDown,
	faChevronRight,
	faFloppyDisk,
	faCircleInfo,
	faTriangleExclamation,
	faTimesCircle,
	faCircleCheck,
	faUser,
	faGear,

	faGoogle,
	faGithub,
	faItchIo,
	faYoutube,
	faTwitch,
	faXTwitter,
);
