import { library } from '@fortawesome/fontawesome-svg-core';
import {
	faAngleRight,
	faArrowRightFromBracket,
	faArrowRightToBracket,
	faBars,
	faBinoculars,
	faCartShopping,
	faCheck,
	faChevronDown,
	faChevronLeft,
	faChevronRight,
	faCircleCheck,
	faCircleInfo,
	faCircleQuestion,
	faEnvelope,
	faEye,
	faEyeSlash,
	faFloppyDisk,
	faGauge,
	faGear,
	faGlobe,
	faHeart,
	faMagnifyingGlass,
	faMoon,
	faPaperPlane,
	faRotate,
	faSun,
	faTimes,
	faTimesCircle,
	faTriangleExclamation,
	faUser,
} from '@fortawesome/free-solid-svg-icons';
import {
	faGoogle,
	faGithub,
	faItchIo,
	faTwitch,
	faXTwitter,
	faYoutube,
} from '@fortawesome/free-brands-svg-icons';


library.add(
	// Solid
	faAngleRight,
	faArrowRightFromBracket,
	faArrowRightToBracket,
	faBars,
	faBinoculars,
	faCartShopping,
	faCheck,
	faChevronDown,
	faChevronLeft,
	faChevronRight,
	faCircleCheck,
	faCircleInfo,
	faCircleQuestion,
	faEnvelope,
	faEye,
	faEyeSlash,
	faFloppyDisk,
	faGauge,
	faGear,
	faGlobe,
	faHeart,
	faMagnifyingGlass,
	faMoon,
	faPaperPlane,
	faRotate,
	faSun,
	faTimes,
	faTimesCircle,
	faTriangleExclamation,
	faUser,

	// Brands
	faGoogle,
	faGithub,
	faItchIo,
	faTwitch,
	faXTwitter,
	faYoutube,
);
